[rendering]
max-line-width = 800

[hugo]

# Gebruik gewone <img>-tags:
# output-mode = "img"

# Gebruik Hugo shortcodes:
# {{< vsa src="..." >}}
output-mode = "shortcode"

# Preview-audio (vsa audio / mvsa audio):
# [audio]
# format = "mp3"
